project:
  type: website
  output-dir: docs

website:
  title: "Marginal Notes"
  site-url: "https://dlpereis.github.io/marginal_notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo       # ou flatly, lumen, simplex...
    toc: true