project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - CV_2025_Eng.pdf

website:
  title: "Margin Notes"
  site-url: "https://dlpereis.github.io/margin_notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/dlpereis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
